generatorName: csharp-unity
outputDir: ./generated
inputSpec: mp-sdk-daemon-poc/api/gameserver.openapi.yaml
packageName: com.unity.services.multiplay
additionalProperties:
  unityVersion: "2020.3"
  packageVersion: "0.0.1"
  unityPackageNamespace: "Unity.Services.Multiplay"
  unityServiceName: "Multiplay"
  generateMarkdownDocumentation: true
  usePhpStyleQueryParams: false
  internalAccessOnly: []
  unityPackageDescription: "The Multiplay SDK provides functionality to facilitate Multiplay services."
  useUnityAuthentication: true
  internalAccessOnly: [http, jsonobject, apis, services]
x-recipeEngine:
  externalSpecSource:
    repository: "https://github.com/Unity-Technologies/mp-sdk-daemon-poc"
    branch: main
    sourcePath: "./"
    outputPath: "mp-sdk-daemon-poc"
  moveGeneratorFiles: true
  trackedDir: ./Packages/Public/com.unity.services.multiplay
  preProcessCommands:
    - echo "Done executing pre process commands."
  postProcessCommands:
    - rm -r mp-sdk-daemon-poc
    - rm openapi-generator.log
    - cp -r ./generated/com.unity.services.multiplay/* ../
    - rm -r ./generated
    - echo "Done executing post process commands."
    
